name: SimplePassword
version: '1.0'
main: io.github.hk51503.SimplePassword
api-version: '1.21'
commands:
  command:
    description: "Enter password"
    usage: "/password [PASSWORD]"
    aliases:
      - password